### ISSUE TITLE
Doesn't work in Beta/PTR

### ISSUE THREAD

**Issue by Ammathor** [Stanzilla/kgPanels#2]
On Log in.

>Message: ...ns\kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0.lua:112: attempt to call method 'GetBackdrop' (a nil value)
Time: Sat Oct 10 18:50:36 2020
Count: 1
Stack: ...ns\kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0.lua:112: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0.lua"]:112: in function `EnableEnhancements'
[string "@Interface\AddOns\kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0.lua"]:57: in function `EnhanceBackdrop'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:405: in function <Interface\AddOns\kgPanels\kgPanels.lua:394>
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:801: in function `PlaceFrame'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:716: in function `ApplyLayout'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:514: in function <Interface\AddOns\kgPanels\kgPanels.lua:510>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

---

On trying to bring up the config menu these appear.

>Message: Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua:607: Usage: LibDualSpec:EnhanceOptions(optionTable, target): EnhanceDatabase should be called before EnhanceOptions(optionTable, target).
Time: Sat Oct 10 18:51:43 2020
Count: 1
Stack: Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua:607: Usage: LibDualSpec:EnhanceOptions(optionTable, target): EnhanceDatabase should be called before EnhanceOptions(optionTable, target).
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\Masque\Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua"]:348: in function `EnhanceOptions'
[string "@Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua"]:607: in function <Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua:596>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:634: in function `?'
[string "@Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua"]:94: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5076: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4740: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4776: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: <none>

>Message: Interface\AddOns\kgPanelsConfig\ArtHelper.lua:173: attempt to index field 'artLibrary' (a nil value)
Time: Sat Oct 10 18:51:43 2020
Count: 1
Stack: Interface\AddOns\kgPanelsConfig\ArtHelper.lua:173: attempt to index field 'artLibrary' (a nil value)
[string "@Interface\AddOns\kgPanelsConfig\ArtHelper.lua"]:173: in function `CreateArtMenu'
[string "@Interface\AddOns\kgPanelsConfig\ArtHelper.lua"]:13: in function `InitArt'
[string "@Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua"]:637: in function <Interface\AddOns\kgPanelsConfig\kgPanelsConfig.lua:635>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:634: in function `?'
[string "@Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua"]:94: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5076: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4740: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4776: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: <none>

>Message: Interface\AddOns\kgPanels\kgPanels.lua:636: kgPanelsConfig isn't registed with AceConfigRegistry, unable to open config
Time: Sat Oct 10 18:51:43 2020
Count: 1
Stack: Interface\AddOns\kgPanels\kgPanels.lua:636: kgPanelsConfig isn't registed with AceConfigRegistry, unable to open config
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1861: in function `Open'
[string "@Interface\AddOns\kgPanels\kgPanels.lua"]:636: in function `?'
[string "@Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua"]:94: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5076: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4740: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4776: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = "kgPanelsConfig isn't registed with AceConfigRegistry, unable to open config"

**Comment by drejjmit** [comment]
Getting the same errors

This guy came up with a fix:
https://www.curseforge.com/wow/addons/kg-panels?comment=1296

**Comment by Stanzilla** [comment]
That's fixed
