### ISSUE TITLE
Bug report, prepatch SL

### ISSUE THREAD

**Issue by a268-Beefy** [Stanzilla/kgPanels#3]
Apears on loading of the addon. KgPanels arent working.
Addon version is 1.24

1x ...ns\kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0-3.lua:112: attempt to call method 'GetBackdrop' (a nil value)
[string "@kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0-3.lua"]:112: in function `EnableEnhancements'
[string "@kgPanels\Libs\LibBackdrop-1.0\LibBackdrop-1.0-3.lua"]:57: in function `EnhanceBackdrop'
[string "@kgPanels\kgPanels-1.24.lua"]:405: in function <kgPanels\kgPanels.lua:394>
[string "@kgPanels\kgPanels-1.24.lua"]:801: in function `PlaceFrame'
[string "@kgPanels\kgPanels-1.24.lua"]:716: in function `ApplyLayout'
[string "@kgPanels\kgPanels-1.24.lua"]:514: in function <kgPanels\kgPanels.lua:510>
[string "=[C]"]: ?
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Stanzilla** [comment]
That's fixed
