### ISSUE TITLE
New error in wrath classic ulduar update

### ISSUE THREAD

**Issue by joshlathery** [Stanzilla/kgPanels#8]
Date: 2023-01-17 21:01:50
ID: 6
Error occured in: Global
Count: 2
Message: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: CreateTexture()
   [string "@Interface/AddOns/kgPanels/kgPanels.lua"]:478:
      Interface/AddOns/kgPanels/kgPanels.lua:441
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:66:
      ...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:494: InitializeAddon()
   [string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:619:
      ...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  ArkInventory, v31013.01
  ArkInventoryRules, v31013
  ArkInventorySearch, v31013
  Atlas, vv1.52.05
  AtlasClassicWoW, vv1.52.01
  AtlasLootClassic, v@project-version@
  AtlasLootClassicData, v@project-version@
  AtlasLootClassicDungeonsAndRaids, v@project-version@
  Attune, v310
  Bartender4, v4.14.4
  BetterAlign, v
  ClassicAuraDurations, v3.0
  ClickLinks, v1.0.8
  Clique, vv3.4.12-release
  Dailies, v030
  DBMCore, va119c9f
  DBMSpellTimers, vr144
  DBMStatusBarTimers, va119c9f
  DBMVPVEM, v8a47308
  Decursive, v2.7.8.13
  Details, v
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ExtendedCharacterStats, v3.0.8
  EZJunk, v1.0.2
  Gargul, v5.0.14
  GatherMate2, v1.46.3-classic
  Grid2, v2.1.0
  Grid2LDB, v2.1.0
  Grid2RaidDebuffs, v2.1.0
  Groupie, v1.66
  GTFO, v5.0
  ItemRack, v
  kgPanels, v1.4.1
  TradeSkillMaster, vv4.12.24
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=3fd)

**Comment by FRSMichael** [comment]
KGPanels is not loading any active panels after the latest Ulduar update for me.

**Comment by joshlathery** [comment]
Thank you for fixing this so quickly!
